// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           20
// Async Callback (empty):               1
// Promise callbacks:                    1
// Total number of exported functions:  24

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    stellarnova_sc
    (
        init => init
        upgrade => upgrade
        whitelistToken => whitelist_token
        removeToken => remove_token
        setPaused => set_paused
        setMaxSlippage => set_max_slippage
        setXExchangePair => set_xexchange_pair
        isTokenWhitelisted => is_token_whitelisted
        getWhitelistedTokens => whitelisted_tokens
        getXExchangePair => xexchange_pair
        getOwner => owner
        isPaused => paused
        getMaxSlippage => max_slippage
        getExecutionFeeBps => execution_fee_bps
        createLimitOrder => create_limit_order
        executeLimitOrder => execute_limit_order
        cancelLimitOrder => cancel_limit_order
        getPendingOrders => get_pending_orders
        getUserOrders => get_user_orders
        getOrder => get_order
        setLimitOrderExecutor => set_limit_order_executor
        setExecutionFeeBps => set_execution_fee_bps
        swap_callback => swap_callback
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
